# Generated by Django 4.2.6 on 2023-10-14 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=128)),
                ('incident_spot', models.CharField(max_length=200)),
                ('zip', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('victim_details', models.TextField()),
                ('culprit_details', models.TextField()),
                ('status', models.CharField(default='received', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('zip', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=200)),
                ('zip', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)])),
            ],
        ),
    ]
