# Generated by Django 4.2.7 on 2023-11-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0002_remove_officer_name_officer_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='username',
            field=models.CharField(default='default_username', max_length=150),
        ),
    ]
