# Generated by Django 4.2.7 on 2023-11-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0003_alter_officer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
