# Generated by Django 4.2.7 on 2023-11-15 18:05

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0006_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=django_cryptography.fields.encrypt(models.AutoField(primary_key=True, serialize=False)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=128)),
        ),
    ]
